# Use custom format

format = """
[#](bold green) $username\
$time\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$python\
$zig\
$buf\
$memory_usage\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$status\
$container\
[#](bold green) $character"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 120

# Disable the blank line at the start of the prompt
add_newline = true

[cmd_duration]
min_time = 1
show_milliseconds = false
disabled = false
style = "bold italic red"

[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = '%T'
utc_time_offset = '+4'
